version: '3.8'

services:
  pgdb:
    image: postgres:16.1
    env_file:
      - app/.env
    volumes:
      - pgdbData:/var/lib/postgresql/data

  displaylab:
    build: .
    expose:
      - "8000"
    # Create Super User
    #command: /bin/sh -c "scripts/wait-for-it.sh pgdb:5432 -t 30 && python app/manage.py migrate && python app/createSuperUser.py"

    # Make backup
    #command: /bin/sh -c "scripts/wait-for-it.sh pgdb:5432 -t 30 && python app/manage.py dbbackup && python app/manage.py mediabackup"

    # Restore backup
    #command: /bin/sh -c "scripts/wait-for-it.sh pgdb:5432 -t 30 && python app/manage.py migrate && python app/manage.py dbrestore --noinput && python app/manage.py mediarestore --noinput"
    
    # Run server
    command: /bin/sh -c "scripts/wait-for-it.sh pgdb:5432 -t 30 && python app/manage.py migrate && python app/manage.py runserver 0:8000"
    volumes:
      - .:/DisplayLab
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis
    env_file:
      - app/.env
  
  redis:
    image: redis:7.2.4-alpine
    env_file:
      - app/.env
    command: /bin/sh -c 'redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"'
    volumes:
      - redisData:/data
    
volumes:
  pgdbData:
  redisData:
