# Generated by Django 5.0 on 2024-01-08 22:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_projetos_capa_projetos_deletado_projetos_gosteis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='pagina',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
