# Generated by Django 5.0 on 2024-01-08 23:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_projetos_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='pagina',
            field=tinymce.models.HTMLField(),
        ),
    ]
