# Generated by Django 5.0 on 2024-01-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_projetos_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='pagina',
            field=models.TextField(default=''),
        ),
    ]
