# Generated by Django 5.0 on 2024-01-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0017_alter_colecaodeimagem_colecao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='colecaoDeImagem',
            new_name='projetoColecaoDeImagem',
        ),
    ]
