# Generated by Django 5.0 on 2026-03-26 19:49

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(default='', max_length=512, unique=True)),
                ('url', models.CharField(default='', max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='membroCarouselColecaoDeImagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colecao', models.SlugField(default='', max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='membroCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oculto', models.BooleanField(default=False)),
                ('categoria', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='membroCarouselImagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to=main.models.image_upload_path)),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.membrocarouselcolecaodeimagem', to_field='colecao')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oculto', models.BooleanField(default=False)),
                ('nome', models.CharField(default='', max_length=200)),
                ('saibaMais', models.CharField(default='', max_length=512)),
                ('foto', models.CharField(default='', max_length=512)),
                ('descricao', models.CharField(default='', max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.membrocategoria', to_field='categoria')),
            ],
        ),
    ]
