# Generated by Django 5.0 on 2024-01-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensdocarousel',
            name='imagem',
            field=models.CharField(default='', max_length=512, unique=True),
        ),
        migrations.AddField(
            model_name='itensdocarousel',
            name='url',
            field=models.CharField(default='', max_length=512, unique=True),
        ),
        migrations.AddField(
            model_name='membros',
            name='categoria',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='membros',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membros',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='membros',
            name='linkedin',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='membros',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='membros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
