# Generated by Django 5.0 on 2024-01-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_membro_foto_membro_saibamais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='linkedin',
        ),
    ]
