# Generated by Django 5.0 on 2024-01-11 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categoria', to_field='categoria'),
        ),
    ]
