# Generated by Django 5.0 on 2024-01-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='capa',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='revista',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revista',
            name='gosteis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revista',
            name='pagina',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='revista',
            name='resumo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='revista',
            name='titulo',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='revista',
            name='url',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='revista',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
