# Generated by Django 5.0 on 2024-01-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0002_revista_capa_revista_deletado_revista_gosteis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='url',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
