# Generated by Django 5.0 on 2024-01-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0003_alter_revista_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='edicao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
