# Generated by Django 5.0 on 2024-01-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0004_revista_edicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='autor',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
