# Generated by Django 5.0 on 2024-01-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0005_revista_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='autor',
            field=models.CharField(default='', max_length=250),
        ),
    ]
