# Generated by Django 5.0 on 2024-01-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0011_alter_revista_edicao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revista',
            old_name='deletado',
            new_name='oculto',
        ),
    ]
