# Generated by Django 5.0 on 2024-01-14 02:13

import django.db.models.deletion
import revista.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0012_rename_deletado_revista_oculto'),
    ]

    operations = [
        migrations.CreateModel(
            name='revistaColecaoDeImagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colecao', models.SlugField(default='', max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='revistaImagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to=revista.models.image_upload_path)),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revista.revistacolecaodeimagem', to_field='colecao')),
            ],
        ),
    ]
