# Generated by Django 5.0 on 2026-03-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0013_revistacolecaodeimagem_revistaimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='local_publicacao',
            field=models.URLField(default='', max_length=512),
        ),
    ]
