# Generated by Django 5.0 on 2026-03-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0014_revista_local_publicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revista',
            old_name='local_publicacao',
            new_name='url_local_publicacao',
        ),
    ]
