# Generated by Django 5.0 on 2026-06-09 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=250, unique=True)),
                ('dataHora', models.DateTimeField(default=datetime.datetime.now)),
                ('conteudo', models.TextField(blank=True, default='')),
                ('capa', models.CharField(blank=True, default='', max_length=512)),
                ('url_youtube', models.URLField(blank=True, default='', max_length=512)),
                ('convidado', models.CharField(blank=True, default='', max_length=250)),
                ('apresentadores', models.CharField(blank=True, default='', max_length=250)),
                ('roteirista', models.CharField(blank=True, default='', max_length=250)),
                ('url', models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                'ordering': ['-dataHora'],
            },
        ),
    ]
