# Generated by Django 5.0 on 2025-12-29 14:17

import alumni.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=250, unique=True)),
                ('descricao', models.CharField(default='', max_length=250)),
                ('perfilLinkedIn', models.URLField(default='', max_length=512)),
                ('perfilLattes', models.URLField(default='', max_length=512)),
                ('foto', models.ImageField(default='alumni/default.jpg', upload_to=alumni.models.aluno_upload_path)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='edicao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edicao', models.PositiveIntegerField(default=0, unique=True)),
            ],
        ),
    ]
