# Generated by Django 5.0 on 2026-03-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='funcao',
            field=models.CharField(default='', max_length=255),
        ),
    ]
