# Generated by Django 5.0 on 2024-01-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_itensdocarousel_imagem_itensdocarousel_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItensDoCarousel',
            new_name='carouselItem',
        ),
        migrations.RenameModel(
            old_name='Membros',
            new_name='Membro',
        ),
    ]
