# Generated by Django 5.0 on 2024-01-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_deletado_membro_oculto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='membroCategoria',
        ),
    ]
