# Generated by Django 5.0 on 2024-01-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_categoria_membrocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrocategoria',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
