# Generated by Django 5.0 on 2024-01-14 02:40

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_membrocategoria_oculto'),
    ]

    operations = [
        migrations.CreateModel(
            name='membroCarouselColecaoDeImagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colecao', models.SlugField(default='', max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='membroCarouselImagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to=main.models.image_upload_path)),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.membrocarouselcolecaodeimagem', to_field='colecao')),
            ],
        ),
    ]
