# Generated by Django 5.0 on 2024-01-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='pagina',
            field=models.TextField(default=''),
        ),
    ]
