# Generated by Django 5.0 on 2024-01-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_rename_projetos_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='url',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
