# Generated by Django 5.0 on 2024-01-11 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_alter_projeto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
