# Generated by Django 5.0 on 2024-01-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_projeto_datahora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='deletado',
            new_name='oculto',
        ),
    ]
