# Generated by Django 5.0 on 2024-01-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_projetoimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projetoImage',
            new_name='projetoImagem',
        ),
    ]
