# Generated by Django 5.0 on 2024-01-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_alter_projetoimagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetoimagem',
            name='imagem',
            field=models.ImageField(upload_to='./projetos/static/uploads'),
        ),
    ]
