# Generated by Django 5.0 on 2024-01-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_alter_projetoimagem_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetoimagem',
            old_name='pasta',
            new_name='colecao',
        ),
    ]
