# Generated by Django 5.0 on 2024-01-14 00:13

import projetos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_rename_pasta_projetoimagem_colecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='colecaoDeImagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colecao', models.SlugField(default='', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='projetoimagem',
            name='imagem',
            field=models.ImageField(upload_to=projetos.models.image_upload_path),
        ),
    ]
