# Generated by Django 5.0 on 2024-01-14 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0016_colecaodeimagem_alter_projetoimagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecaodeimagem',
            name='colecao',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='projetoimagem',
            name='colecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.colecaodeimagem', to_field='colecao'),
        ),
    ]
