# Generated by Django 5.0 on 2026-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0018_rename_colecaodeimagem_projetocolecaodeimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='url_local_publicacao',
            field=models.URLField(default='', max_length=512),
        ),
    ]
