# Generated by Django 5.0 on 2025-12-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('url_fonte', models.URLField(unique=True)),
                ('url_imagem', models.TextField(blank=True, null=True)),
                ('fonte', models.CharField(max_length=255)),
                ('data_publicacao', models.DateTimeField()),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
