# Generated by Django 5.0 on 2024-01-11 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0006_alter_revista_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
