# Generated by Django 5.0 on 2024-01-11 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0010_edicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='edicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revista.edicao', to_field='edicao'),
        ),
    ]
